"""add attendance table

Revision ID: 6f8f9de11d3d
Revises: ecf84415c3c9
Create Date: 2026-02-19 20:15:41.403154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f8f9de11d3d'
down_revision = 'ecf84415c3c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
